# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9daa2f5d12ae070a82f27fe46a68497ccbfa64029c4d18b74f11b0dd469fb61c11fcc493d0883fd867ab8f33d08fa78e65b87c605a48587b1c2c0a62aae20e

test:
  secret_key_base: c436656b7308c87e6f65538da9492e2259e13c803c48d68bcee2f0050e42bcbdaab464e60d826ccb4cb2e8bcf1129cc6545dcd2c06f0e22ab1f7ab98cba7fad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
